version: "3"

services:
  reverse-proxy:
    restart: always
    image: traefik:v2.7
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      # Certificate
      - --certificatesresolvers.tlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.tlschallenge.acme.email=${CERTIFICATE_EMAIL} # <== Setting email for certs
      - --certificatesresolvers.tlschallenge.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert informationcertificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      #- --certificatesresolvers.tlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # Logging for fail2ban
      - --accesslog=true
      - --accesslog.filepath=var/log/access.log
      - --accesslog.filters.statuscodes=400-499
      - --accesslog.bufferingsize=30
      # Default middlewares
      - --entrypoints.web.http.middlewares=https_redirect
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/var/log
    networks:
      - web
    logging:
      options:
        max-size: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

  fail2ban:
    restart: always
    image: crazymax/fail2ban:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/log/traefik:/var/log/traefik:ro
      - ./netdata/fail2ban/log:/var/log/fail2ban.log
      - ./netdata/fail2ban/conf:/etc/fail2ban/jail.local
      - ./fail2ban/data:/data

  traefik-forward-auth:
    restart: always
    image: thomseddon/traefik-forward-auth:2
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - PROVIDERS_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - PROVIDERS_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - SECRET=${SECRET}
      - AUTH_HOST=${AUTH_DOMAIN}
      - LOG_LEVEL=debug
    logging:
      options:
        max-size: 10m
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.traefik-forward-auth-web.loadbalancer.server.port=4181"
      # HTTP
      - "traefik.http.routers.traefik-forward-auth-web.rule=Host(`${AUTH_DOMAIN}`) || Host(`www.${AUTH_DOMAIN}`)"
      - "traefik.http.routers.traefik-forward-auth-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.traefik-forward-auth-secured.rule=Host(`${AUTH_DOMAIN}`) || Host(`www.${AUTH_DOMAIN}`)"
      - "traefik.http.routers.traefik-forward-auth-secured.entrypoints=web-secured"
      - "traefik.http.routers.traefik-forward-auth-secured.tls.certresolver=tlschallenge"
      # Auth middleware
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

networks:
  web:
    name: web
    driver: bridge
    internal: false